CREATE TABLE GUEST_MASTER (
    GUEST_ID NUMBER PRIMARY KEY,
    GUEST_NAME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20)
);

CREATE TABLE ROOM_MASTER (
    ROOM_ID NUMBER PRIMARY KEY,
    ROOM_TYPE VARCHAR2(50),
    ROOM_RATE NUMBER
);

CREATE TABLE CHECKIN_CHECKOUT (
    STAY_ID NUMBER PRIMARY KEY,
    GUEST_ID NUMBER,
    ROOM_ID NUMBER,
    CHECKIN_DATE DATE,
    CHECKOUT_DATE DATE,
    EXTRA_CHARGES NUMBER,
    LAST_UPDATED DATE
);

CREATE TABLE STG_GUEST_STAY (
    STAY_ID NUMBER,
    GUEST_NAME VARCHAR2(100),
    ROOM_TYPE VARCHAR2(50),
    CHECKIN_DATE DATE,
    CHECKOUT_DATE DATE,
    STAY_DURATION NUMBER,
    TOTAL_AMOUNT NUMBER,
    LOAD_DATE DATE DEFAULT SYSDATE
);

select * from STG_GUEST_STAY;


CREATE TABLE STAY_AUDIT (
  AUDIT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  STAY_ID NUMBER,
  ACTION_TYPE VARCHAR2(10),
  OLD_DATA VARCHAR2(500),
  NEW_DATA VARCHAR2(500),
  CHANGE_DATE DATE
);

CREATE OR REPLACE PROCEDURE DAILY_REPORT AS
    v_rooms NUMBER;
    v_revenue NUMBER;
BEGIN
    -- Rooms occupied today
    SELECT COUNT(DISTINCT ROOM_TYPE)
    INTO v_rooms
    FROM STG_GUEST_STAY
    WHERE TRUNC(CHECKIN_DATE) = TRUNC(SYSDATE);

    -- Total revenue today
    SELECT NVL(SUM(TOTAL_AMOUNT),0)
    INTO v_revenue
    FROM STG_GUEST_STAY
    WHERE TRUNC(CHECKIN_DATE) = TRUNC(SYSDATE);

    DBMS_OUTPUT.PUT_LINE('Rooms Occupied Today: ' || v_rooms);
    DBMS_OUTPUT.PUT_LINE('Total Revenue Today: ' || v_revenue);
END;
/

SET SERVEROUTPUT ON;
EXEC DAILY_REPORT;

CREATE OR REPLACE TRIGGER TRG_STAY_AUDIT
AFTER INSERT OR UPDATE ON STG_GUEST_STAY
FOR EACH ROW
BEGIN
    INSERT INTO STAY_AUDIT (
        STAY_ID,
        ACTION_TYPE,
        ACTION_DATE
    )
    VALUES (
        :NEW.STAY_ID,
        CASE
            WHEN INSERTING THEN 'INSERT'
            WHEN UPDATING THEN 'UPDATE'
        END,
        SYSDATE
    );
END;
/
